/**
 * Writes the TextMate grammar's keyword alternations from the parser's keyword tables.
 *
 * The two used to be independent lists, and they drifted: `Save`, `SaveRecord`, `Delete`, `Clear`
 * and `Find` were statement verbs the parser understood for a long time while the grammar left
 * them with no scope at all. Generating one from the other means a verb added to `keywords.ts`
 * is coloured the next time this runs, and `test/grammar.test.ts` fails until it does.
 *
 * Only the entries listed in `GENERATED` are touched. The structured rules -- `WebSet psX`,
 * `Set psX`, `Send Method`, and the declaration forms -- stay hand-written, because they capture
 * the *following* identifier as well and that is not derivable from a word list.
 *
 * Run with `npm run grammar-sync`. It must be a no-op on a clean tree.
 *
 * Not covered: `language-configuration.json` duplicates block-keyword knowledge in its indent
 * regexes. That is structural (which words open and close a block), not a keyword set, so it
 * stays by hand.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  BLOCK_WORDS,
  BUILTIN_TYPES,
  DECLARATION_WORDS,
  CONTROL_VERBS,
  DATABASE_VERBS,
  MESSAGE_VERBS,
  OTHER_VERBS
} from '../packages/df-parser/src/keywords';

const GRAMMAR = join(
  __dirname,
  '..',
  'packages',
  'vscode-dataflex',
  'syntaxes',
  'dataflex.tmLanguage.json'
);

/**
 * Verbs already handled by a structured rule earlier in the pattern list.
 *
 * Listing them again in a bare alternation would be harmless -- the earlier rule wins -- but it
 * would also be a lie about which rule colours them, and it would scope the verb without its
 * argument on lines where the structured rule did match.
 */
const STRUCTURED = new Set(['set', 'get', 'webset', 'webget', 'send', 'broadcast', 'delegate', 'forward']);

/**
 * Display casing for names that a naive title-case gets wrong.
 *
 * Presentation only: every generated pattern is `(?i)`, so a name missing from this map is
 * matched exactly the same, it just reads less like DataFlex in the committed file.
 */
const DISPLAY: ReadonlyMap<string, string> = new Map([
  ['webset', 'WebSet'],
  ['webget', 'WebGet'],
  ['rowid', 'RowId'],
  ['datetime', 'DateTime'],
  ['timespan', 'TimeSpan'],
  ['bigint', 'BigInt'],
  ['ubigint', 'UBigInt'],
  ['uinteger', 'UInteger'],
  ['uchar', 'UChar'],
  ['ushort', 'UShort'],
  ['dword', 'DWord'],
  ['uwide', 'UWide'],
  ['wstring', 'WString'],
  ['longptr', 'LongPtr'],
  ['ole_handle', 'OLE_Handle'],
  ['ole_color', 'OLE_Color'],
  ['external_function32', 'External_Function32'],
  ['external_procedure32', 'External_Procedure32']
]);

function display(word: string): string {
  const override = DISPLAY.get(word);
  if (override !== undefined) {
    return override;
  }
  return word
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('_');
}

/**
 * An alternation over the given words.
 *
 * Sorted longest-first. `\b` already prevents `end` from matching inside `end_transaction` --
 * `_` is a word character -- but the ordering costs nothing and does not rely on that.
 */
function alternation(words: Iterable<string>, suffix = ''): string {
  const sorted = [...words].sort((a, b) => b.length - a.length || a.localeCompare(b));
  return `(?i)\\b(${sorted.map(display).join('|')})\\b${suffix}`;
}

const messageVerbs = MESSAGE_VERBS.filter((verb) => !STRUCTURED.has(verb));

/** The repository entries this script owns, whole. Anything not listed here is hand-written. */
const GENERATED: Record<string, { comment: string; name: string; match: string }> = {
  'verbs-database': {
    comment: 'Generated by scripts/sync-grammar.ts from DATABASE_VERBS. Do not edit by hand.',
    name: 'keyword.other.database.dataflex',
    match: alternation(DATABASE_VERBS)
  },
  'verbs-message': {
    comment:
      'Generated by scripts/sync-grammar.ts from MESSAGE_VERBS, less the verbs the structured rules in #message-verbs already colour. Do not edit by hand.',
    name: 'keyword.other.message.dataflex',
    match: alternation(messageVerbs)
  },
  'verbs-other': {
    comment: 'Generated by scripts/sync-grammar.ts from OTHER_VERBS. Do not edit by hand.',
    name: 'keyword.other.dataflex',
    match: alternation(OTHER_VERBS)
  },
  'control-keywords': {
    comment:
      'Generated by scripts/sync-grammar.ts from CONTROL_VERBS plus the block words. Do not edit by hand.',
    name: 'keyword.control.dataflex',
    match: alternation([...CONTROL_VERBS, ...BLOCK_WORDS])
  },
  'declaration-keywords': {
    comment:
      'Generated by scripts/sync-grammar.ts from DECLARATION_WORDS. Do not edit by hand.',
    name: 'keyword.other.dataflex',
    match: alternation(DECLARATION_WORDS)
  },
  types: {
    comment: 'Generated by scripts/sync-grammar.ts from BUILTIN_TYPES. Do not edit by hand.',
    name: 'storage.type.dataflex',
    match: alternation(BUILTIN_TYPES, '(\\[\\])?')
  }
};

/** Where the generated entries sit in the pattern list, relative to the hand-written ones. */
const PATTERN_ORDER = [
  'comments',
  'preprocessor',
  'annotations',
  'strings',
  'object-declaration',
  'class-declaration',
  'method-declaration',
  'struct-declaration',
  'property-declaration',
  'use-directive',
  // Structured message rules first: they capture the verb *and* its argument, so they must beat
  // the bare alternations below.
  'message-verbs',
  'block-keywords',
  'verbs-database',
  'verbs-message',
  'verbs-other',
  'control-keywords',
  'declaration-keywords',
  'types',
  'constants',
  'numbers',
  'operators'
];

const grammar = JSON.parse(readFileSync(GRAMMAR, 'utf8')) as {
  patterns: { include: string }[];
  repository: Record<string, unknown>;
};

for (const [key, entry] of Object.entries(GENERATED)) {
  grammar.repository[key] = entry;
}

const missing = PATTERN_ORDER.filter((key) => grammar.repository[key] === undefined);
if (missing.length > 0) {
  console.error(`missing repository entries: ${missing.join(', ')}`);
  process.exit(1);
}
grammar.patterns = PATTERN_ORDER.map((include) => ({ include: `#${include}` }));

// Keep the repository in pattern order too, so the file reads in the order the engine tries it.
const ordered: Record<string, unknown> = {};
for (const key of PATTERN_ORDER) {
  ordered[key] = grammar.repository[key];
}
for (const [key, value] of Object.entries(grammar.repository)) {
  if (ordered[key] === undefined) {
    ordered[key] = value;
  }
}
grammar.repository = ordered;

writeFileSync(GRAMMAR, `${JSON.stringify(grammar, undefined, 2)}\n`, 'utf8');

const counts = Object.entries(GENERATED).map(
  ([key, entry]) => `${key}: ${entry.match.split('|').length}`
);
console.log(`wrote ${GRAMMAR}`);
console.log(counts.join('\n'));
